theme = "my-theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
J = ["move_line_down", "move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down"]
K = ["move_line_up", "move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up"]
H = "goto_line_start"
L = "goto_line_end"
V = ["extend_line_below", "select_mode"]
"C-r" = "redo"
D = ["select_mode", "goto_line_end", "delete_selection"]
"C-a" = ["goto_file_start","extend_line_below", "select_mode", "goto_last_line"]
g = { h = "hover"}
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
"C-\\" = ":sh kitty @ launch --type tab --allow-remote-control --title lazygit --cwd current"
 
[keys.normal.space]
c = ":buffer-close"
w = ":update"
q = ":quit"
J = "jumplist_picker"
j = "goto_previous_buffer"
k = "goto_next_buffer"
"\\" = ":sh kitty @ launch --allow-remote-control --title lazygit --cwd current"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" } 
"C-space" = "completion"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
y ="yank_main_selection_to_clipboard"
P = "replace_selections_with_clipboard"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode","version-control","spinner","file-name"]

