theme = "custom-tokyonight-storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
end-of-line-diagnostics = "hint"
completion-timeout = 5
completion-trigger-len = 1
default-yank-register = "+"      # use system clipboard for yank and paste actions

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = [
  "mode",
  "version-control",
  "spinner",
  "file-name",
  "file-modification-indicator",
  "read-only-indicator",
  "file-type",
]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
J = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]
K = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
G = "goto_last_line"
H = "goto_first_nonwhitespace"
L = "goto_line_end"
V = ["extend_line_below", "select_mode"]
x = ["extend_line_below", "select_mode"]
"C-r" = "redo"
D = ["select_mode", "goto_line_end", "delete_selection"]
"C-a" = "select_all"
g = { h = "hover" }
"C-space" = "expand_selection"
# x = ["goto_line_start", "select_mode", "goto_line_end_newline"]

[keys.normal.space]
e = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open $(realpath %{buffer_name} 2>/dev/null)"
E = "file_explorer_in_current_buffer_directory"
# e = "file_explorer_in_current_buffer_directory"
# E = "file_explorer"
w = ":update"
J = "jumplist_picker"
j = "goto_previous_buffer"
k = "goto_next_buffer"
o = "file_picker_in_current_buffer_directory"
z = "suspend"


[keys.normal.space.g]
g = "changed_file_picker"
# Show blame info for current line
l = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
# l = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"
# l = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"
# Copy git provider url for this file and line
# o = ":sh get_git_url %{buffer_name} %{cursor_column} | pbcopy"
# b = ":sh gh browse %{buffer_name}:%{cursor_line} -c=%sh{latest_pushed_commit}"

[keys.normal.m]
# Workaround for us to be able to replace highlighted/selected text with P keymap.
i = ["select_mode", "select_textobject_inner"]
a = ["select_mode", "select_textobject_around"]

[keys.normal.space.q]
q = ":quit"
c = ":buffer-close"
C = ":buffer-close-others"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }
"C-space" = "completion"


[keys.select]
P = "replace_with_yanked"
V = ["extend_line_below", "select_mode"]
H = "goto_line_start"
L = "goto_line_end"
J = [
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
  "extend_line_down",
]
K = [
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
  "extend_line_up",
]

# [keys.normal.space.g]
# d = "changed_file_picker"
# NOTE: this is problematic. A lot of issues occur when using this. You no longer can't use <c-o> in lazygit even used outside of helix.
# g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
# you need to set allow_remote_control to yes in order to use kitty @ launch
# g = [
#   ":sh kitty @ launch --type tab --allow-remote-control --title lazygit --cwd current --copy-env lazygit",
# ]


# NOTE: create new file relative to current buffer path
# Ref: https://github.com/helix-editor/helix/discussions/6052
# :o <C-r>%


# NOTE: move/rename current buffer
# Ref: https://github.com/helix-editor/helix/issues/6825#issuecomment-2499152942
# :move <C-r>%

# NOTE:
# Ref: https://github.com/helix-editor/helix/discussions/12174#discussioncomment-11437600
# You can also use <C-w> to remove the last segment when using <C-r>% command expansion


# NOTE:
# Ref: https://www.reddit.com/r/HelixEditor/comments/14v300b/how_to_select_within_tags/
# To select within html tags, move cursor above inside of html tags then use <Alt-o>
