theme = "my-theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
# TODO: not working
# "diagnostic.error" = { underline = { style = "curl", color = "red" } }

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space = { c = ":buffer-close" }
# J = "10j"
# K = "10k"
 
[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" } 
"C-space" = "completion"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode","version-control", "spinner","file-name"]
