theme = "my-theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space = { c = ":buffer-close", w = ":update", q = ":quit" }
J = ["move_line_down", "move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down"]
K = ["move_line_up", "move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up"]
H = "goto_line_start"
L = "goto_line_end"
V = ["extend_line_below", "select_mode"]
"C-r" = "redo"
D = ["select_mode", "goto_line_end", "delete_selection"]
  
[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" } 
"C-space" = "completion"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode","version-control","spinner","file-name"]

