theme = "my_tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
J = ["move_line_down", "move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down","move_line_down"]
K = ["move_line_up", "move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up","move_line_up"]
H = "goto_line_start"
L = "goto_line_end"
V = ["extend_line_below", "select_mode"]
"C-r" = "redo"
D = ["select_mode", "goto_line_end", "delete_selection"]
"C-a" = ["goto_file_start","extend_line_below", "select_mode", "goto_last_line", "extend_line_below"]
g = { h = "hover"}
# p = "paste_clipboard_after"
# P = "paste_clipboard_before"
# y = "yank_main_selection_to_clipboard"
 
[keys.normal.space]
w = ":update"
J = "jumplist_picker"
j = "goto_previous_buffer"
k = "goto_next_buffer"

[keys.normal.space.q]
q = ":quit"
c = ":buffer-close"
C = ":buffer-close-others"

[keys.normal.space.g]
g = [":sh kitty @ launch --type tab --allow-remote-control --title lazygit --cwd current --copy-env lazygit" ]

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" } 
"C-space" = "completion"

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
J = ["extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down", "extend_line_down"]
K = ["extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up", "extend_line_up"]
# y ="yank_main_selection_to_clipboard"
# P = "replace_selections_with_clipboard"
# p = "replace_selections_with_clipboard"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode","version-control","spinner","file-name"]

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"

