[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "auto"

[[language]]
name = "html"
# formatter = { command = 'biome', args = ["format", "--write", "--stdin-file-path"] }
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "emmet-lsp",
]

[[language]]
name = "json"
formatter = { command = 'biome', args = [
  "format",
  "--write",
  "--stdin-file-path",
  "file.json",
] }

[[language]]
name = "css"
# formatter = { command = 'biome', args = [
#   "format",
#   "--write",
#   "--stdin-file-path",
# ] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
formatter = { command = 'biome', args = [
  "check",
  "--write",
  "--stdin-file-path",
  "file.js",
] }
auto-format = true
language-servers = [
  "typescript-language-server",
  # "vscode-eslint-language-server",
  "biome",
]

[[language]]
name = "typescript"
formatter = { command = 'biome', args = [
  "check",
  "--write",
  "--stdin-file-path",
  "file.ts",
] }
auto-format = true
language-servers = [
  "typescript-language-server",
  # "vscode-eslint-language-server",
  "biome",

]

[[language]]
name = "jsx"
formatter = { command = 'biome', args = [
  "check",
  "--write",
  "--stdin-file-path",
  "file.jsx",
] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "emmet-lsp",
  # "vscode-eslint-language-server",
  "biome",
]

[[language]]
name = "tsx"
formatter = { command = 'biome', args = [
  "check",
  "--write",
  "--stdin-file-path",
  "file.tsx",
] }
auto-format = true
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "emmet-lsp",
  # "vscode-eslint-language-server",
  "biome",
]

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls", "eslint"]
