[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.tsx"] }
auto-format = true

# Deno's formatter is written in Rust and is very fast compared to Prettier
# but has different config file so we still use prettier.
# [[language]]
# name = "javascript"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
# auto-format = true

# [[language]]
# name = "json"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json" ] }

# [[language]]
# name = "markdown"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "md" ] }
# auto-format = true

# [[language]]
# name = "typescript"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
# auto-format = true

# [[language]]
# name = "jsx"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "jsx" ] }
# auto-format = true

# [[language]]
# name = "tsx"
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "tsx" ] }
# auto-format = true