inherits = "tokyonight_storm"

# Override Theme
"ui.selection" = { bg = "#2E3C64" }
"ui.selection.primary" = { bg = "#2E3C64" }
"ui.bufferline" = { bg = "bg-menu", fg = "gray" }
"ui.bufferline.active" = { fg = "white", bg = "bg", modifiers = ["bold"] }
"ui.statusline.separator" = "|"
"ui.linenr" = { fg = "comment", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "orange", modifiers = [""] }

# Treesitter
# constructor = { fg = "red" }
attribute = { fg = "green" }
punctuation = { fg = "fg-dark" }
"ui.text.directory" = { fg = "comment" }

# Setting the bg to an empty string fixes highlighting in the picker preview
# (especially in grep), where the matched whole line is not highlighted—only the background.
"ui.text" = { fg = "fg", bg = "" }
