inherits = "tokyonight_storm"

# Override Theme
"ui.bufferline" = { bg = "bg-menu", fg = "gray" }
"ui.bufferline.active" = { fg = "white", bg = "bg" }
"ui.statusline.separator" = "|"
"ui.linenr" = { fg = "comment", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "white", modifiers = [""] }
"ui.virtual.jump-label" = "orange"
