inherits = "tokyonight_storm"

# "diagnostic.error" = { underline = { style = "curl", color = "red" } }
# "diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
# "diagnostic.info" = { underline = { style = "curl", color = "green" } }
# "diagnostic.hint" = { underline = { style = "curl", color = "blue" } }

# Syntax Highlighting

# Override Theme
"ui.bufferline" = { bg = "background_menu", fg = "gray" }
"ui.bufferline.active" = { fg = "white", bg = "background", modifiers = [] }
"ui.statusline.separator" = "white"
"ui.linenr" = { fg = "comment", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "white", modifiers = [""] }
