inherits = "my_tokyonight"

# Override Theme
"ui.bufferline" = { bg = "bg-menu", fg = "gray" }
"ui.bufferline.active" = { fg = "white", bg = "bg" }
"ui.statusline.separator" = "|"
"ui.linenr" = { fg = "comment", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "white", modifiers = [""] }
"ui.virtual.jump-label" = "orange"

[palette]
border = "#1d202f"
bg = "#24283b"
bg-inlay = "#233745"
bg-highlight = "#373d5a"
bg-menu = "#1f2335"
bg-visual = "#2e3c64"
border-highlight = "#29a4bd"
